### ISSUE TITLE
How do I make it work?

### ISSUE THREAD

**Issue by Geniusssmit** [joaquintorres/autosubsync-mpv#2]
I set
```
default_subsync_location = "C:\Users\PAUL\AppData\Local\Programs\Python\Python38\Scripts\ffsubsync.exe"
```
and
```
subsync = "C:\Users\PAUL\AppData\Local\Programs\Python\Python38\Scripts\ffsubsync.exe"
```
so when I press "n" nothing happens. What else should I do?
I also tried 
```
subsync = "C:\Users\PAUL\AppData\Local\Programs\Python\Python38\Scripts\ffsubsync"
```
and just
```
subsync = "C:\Users\PAUL\AppData\Local\Programs\Python\Python38\Scripts"
```

**Comment by Geniusssmit** [comment]
I'm not Windows 10 if that matters

**Comment by Geniusssmit** [comment]
> I'm on Windows 10 if that matters

**Comment by Bocchio** [comment]
Disclaimer: I'm not on windows

But I'm pretty sure you need to slashes, the first one is the escape character

That is something like:

`default_subsync_location = "C:\\Users\\PAUL\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\ffsubsync.exe"`

**Comment by Bocchio** [comment]
Ok, there's a bug when detecting the operating systems. In plain lua the line `package.cpath:match("%p[\\|/]?%p(%a+)")` would work, but when running it inside mpv it just gets replaced with the name of the binary. I'll look a bit more into it.

For the time being, an easy work around would be inserting a few lines of code after the line that says `binary_format = nil`:

```
function os.name()
    return "Windows"
end
```

**Comment by Bocchio** [comment]
I've just sent a pull request. It should work out of the box without changing the file.

**Comment by joaquintorres** [comment]
I accepted the pull request. Using another location for `ffsubsync` also works with double backslashes in the path like @Bocchio suggested. I tried both `subsync = "C:\\Users\\PAUL\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\ffsubsync"` and `subsync = "C:/Users/PAUL/AppData/Local/Programs/Python/Python38/Scripts/ffsubsync"` instead of backslashes, and they seem to work just fine. The issue @Bocchio mentioned seems to break manual replacement in Windows so @Geniusssmit , you can download the latest fixed version and try the paths I just mentioned. That should probably fix it.

**Comment by joaquintorres** [comment]
@Geniusssmit Please let me know if it works for you like it did for me and @Bocchio, or if it still persists.

**Comment by Geniusssmit** [comment]
Yes, it works! though "Python38" in the path will be different for everyone I would imagine

**Comment by Geniusssmit** [comment]
next thing would be to make it compatible with that script I guess https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua , so you can sync entire show, man that would be wonderful!

**Comment by joaquintorres** [comment]
Great! Yeah, I guess default path detection will be more useful to Linux/MacOS users for now, I'll check if there's a better way to get the right path in Windows with all the Python variants, it's also a bit annoying when using Anaconda. I'll update the README so at least Windows users can replace their own path without this issue. 
I think synchronizing all the files in a folder/playlist would be easier and more comfortable straight up using `ffsubsync` (directly or in a script) instead of the mpv plugin, doing it from the player would be a bit messy compared to only syncing when needed, in the current file. Feel free to fork the project and modify it to best suit your needs.
And thanks for your useful feedback!

**Comment by Bocchio** [comment]
> Yes, it works! though "Python38" in the path will be different for everyone I would imagine

Yes, I'm aware... sadly there's no unified location as documented in https://docs.python.org/3/using/windows.html#installing-without-ui

It might also be possible to make a reasonable guess about the location though. But that would take code that could potentially break things, so I think it's better to go one step at a time.

**Comment by joaquintorres** [comment]
> next thing would be to make it compatible with that script I guess https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua , so you can sync entire show, man that would be wonderful!

Reconsidering, maybe it would be useful for those who don't want to use `ffsubsync` from the commandline or batch the process, and it could allow you to sync everything while watching the first episode, so I'll write it down as a possible future improvement.
