### ISSUE TITLE
Problems using script after updating python.

### ISSUE THREAD

**Issue by dddd66** [joaquintorres/autosubsync-mpv#20]
I recently updated python to 3.10, when doing so, i noticed in mpv that autosubsync was no longer working for whatever reason, whevener i try to use it with ffsubsync it gives this error: "couldn't add synchronized subtitle", alass: "subtitle synchronization failed", can you help me sort out this bug? i'm not really sure what caused it, it just started happening after i updated python to do a project, i installed python 3.9.13, uninstalled every other python version i had, reinstalled ffsubsync and autosubsync on mpv and yet i i'm not able to use the script.

Windows 10 x64 21H1, mpv 0.34.0-468-gba81e4ed88, Python 3.9.13, FFmpeg version: git-2022-09-17-ed83a3a5b

**Comment by tatsumoto-ren** [comment]
When you upgrade python, usually you have to reinstall all `pip` packages installed in the home directory because they are not automatically transferred to a newer python version. On GNU the packages are stored in `~/.local/lib/python3.XX`. You also have to be sure that the directory where `pip` stores executable scripts is added to the `PATH`. 

Try upgrading from Windows. I recommend installing Arch Linux, but other distros of GNU are also fine.

https://tatsumoto.neocities.org/blog/our-immersion-learning-toolset.html#gnulinux

**Comment by dddd66** [comment]
It's not possible for me to switch to GNU/Linux right now, but certainly i'm doing so in the future. For now i have to live without this script since i tried every possible fix i could imagine. I think it's related to windows at this point.

**Comment by tatsumoto-ren** [comment]
Check if `ffsubsync` works properly by itself, e.g. when you run it from the terminal. And as I mentioned before, check your PATH.

**Comment by dddd66** [comment]
Solved the problem. It was some weird issue with Windows not properly recognizing ffmpeg in the path.

**Comment by Stoppels** [comment]
What specifically helped solve this for you? I have the same issue on an M1 Mac (downgrading to Py9 didn't fix it, it just made the error so generic I don't know what's wrong lol) whereas my older Intel Mac works fine. Homebrew uses different folders on Intel and Apple Silicon, but it's set in the path so it _should_ work…
